version: '3'

services:
  mongo:
    image: mongo
    restart: always
    env_file: ./.env

  company_ideas:
    image: vsokoltsov/company_ideas
    container_name: company_ideas
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    volumes:
      - .:/company_ideas
    ports:
     - "8000:8000"
    depends_on:
      - mongo
